Packaging/fedora/devilutionx.desktop usr/share/applications/
obj-x86_64-linux-gnu/devilutionx     	usr/share/games/diablo/
Packaging/resources/Diablo_48.png	usr/share/icons/hicolor/48x48/apps
Packaging/resources/Diablo_32.png	usr/share/icons/hicolor/32x32/apps
Packaging/resources/16.png		usr/share/icons/hicolor/16x16/apps
Packaging/resources/CharisSILB.ttf	usr/share/fonts/truetype
Packaging/resources/16.png 		usr/share/icons/hicolor/16x16/apps/
Packaging/resources/Diablo_32.png 	usr/share/icons/hicolor/32x32/apps/
Packaging/resources/Diablo_48.png 	usr/share/icons/hicolor/48x48/apps/

