#pragma once

#define DSBCAPS_PRIMARYBUFFER DVL_DSBCAPS_PRIMARYBUFFER
#define DSBCAPS_STATIC DVL_DSBCAPS_STATIC
#define DSBCAPS_CTRLPAN DVL_DSBCAPS_CTRLPAN
#define DSBCAPS_CTRLVOLUME DVL_DSBCAPS_CTRLVOLUME

#define WAVE_FORMAT_PCM DVL_WAVE_FORMAT_PCM

#define ERROR_SUCCESS 0L

#define _FACDS 0x878
#define MAKE_DSHRESULT(code) MAKE_HRESULT(1, _FACDS, code)

#define E_NOINTERFACE 0x80004002
#define DSERR_PRIOLEVELNEEDED MAKE_DSHRESULT(70)
#define DSERR_BADFORMAT MAKE_DSHRESULT(100)
#define DSERR_NODRIVER MAKE_DSHRESULT(120)
#define DSERR_ALREADYINITIALIZED MAKE_DSHRESULT(130)
#define DSERR_BUFFERLOST MAKE_DSHRESULT(150)
#define DS_OK DVL_DS_OK
#define DSERR_INVALIDCALL MAKE_DSHRESULT(50)
#define DSERR_NOAGGREGATION 0x80040110
#define DSERR_OUTOFMEMORY 0x8007000E
#define DSERR_INVALIDPARAM 0x80070057
#define DSERR_ALLOCATED MAKE_DSHRESULT(10)
#define DSERR_CONTROLUNAVAIL MAKE_DSHRESULT(30)
