#pragma once

#define SW_HIDE DVL_SW_HIDE
#define SW_SHOWNORMAL DVL_SW_SHOWNORMAL

#define SM_CXSCREEN DVL_SM_CXSCREEN
#define SM_CYSCREEN DVL_SM_CYSCREEN

#define E_FAIL DVL_E_FAIL
#define S_OK DVL_S_OK

#define DDERR_INVALIDOBJECT 0x88760082
#define DDERR_OUTOFMEMORY 0x8876000E
#define DD_OK S_OK

#define DDBLTFAST_WAIT 0x00000010

#define PC_RESERVED 0x01
#define PC_NOCOLLAPSE 0x04

#define ERROR_SUCCESS DVL_ERROR_SUCCESS
#define DS_OK DVL_DS_OK
